### demo示例
GET http://127.0.0.1:9000/demo/get-message?id=2 HTTP/1.1

###
GET http://127.0.0.1:9000/demo/panic-test HTTP/1.1

### 用户模块
#### 发送验证码
POST http://127.0.0.1:9000/user/send-code HTTP/1.1
Content-Type: application/x-www-form-urlencoded

nickname=murane&email=2117907739@qq.com&password=123456aB&repeat_password=123456aB

### 用户注册
POST http://localhost:9000/user/register HTTP/1.1
Content-Type: application/json

{
    "nickname": "murane",
    "email": "2117907739@qq.com",
    "password": "Test123!",
    "repeat_password": "Test123!",
    "verify_code": "2d7b"
}

### 用户登录
#### 用户密码
GET http://localhost:9000/user/login?nickname=murane&password=Test123! HTTP/1.1
#### 邮箱密码
GET http://localhost:9000/user/login?email=1512619344@qq.com&password=Test123! HTTP/1.1
#### 邮箱验证码
GET http://localhost:9000/user/login?email=1512619344@qq.com&verify_code=bdb3 HTTP/1.1

### 用户登出
GET http://localhost:9000/user/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDE1ZWJjOGItZjU0Ny00MDgxLTk0ZjEtZmU3MDQwNzY5ODY1IiwiaXNzIjoiYWktbmV4dXMtYXV0aCIsImV4cCI6MTc2MjU4ODcwNSwiaWF0IjoxNzYxOTgzOTA1fQ.g3O2HUwGwdiOniKpc_C4q0Mpm2DubV93g4JL6rweA_M

### 获取用户信息
GET http://localhost:9000/user/getuserinfo HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDE1ZWJjOGItZjU0Ny00MDgxLTk0ZjEtZmU3MDQwNzY5ODY1IiwiaXNzIjoiYWktbmV4dXMtYXV0aCIsImV4cCI6MTc2MjU4ODcwNSwiaWF0IjoxNzYxOTgzOTA1fQ.g3O2HUwGwdiOniKpc_C4q0Mpm2DubV93g4JL6rweA_M
