@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMDFjMjEwNzItNDdjNi00NTNmLWExMjItZDJiNGRiZjRjMjE2IiwiaXNzIjoiYWktbmV4dXMtYXV0aCIsImV4cCI6MTc2NDIxMzk4MCwiaWF0IjoxNzYzNjA5MTgwfQ.uN8u39JJdhVDgrn3ogPyKFCvUq-5gkbidTQdg4S_jls

### 生图模块
### 文生图: seed 参数为可选
POST http://127.0.0.1:9000/image-generation/image/text2img
Authorization: {{token}}
Content-Type: application/json

{
  "prompt": "一个可爱的白发二次元小萝莉，手里拿着一个棒棒糖",
  "negative_prompt": "",
  "model_id": "qwen-image",
  "width": 1024,
  "height": 1024,
  "num_inference_steps": 20,
  "guidance_scale": 7.5,
  "seed": 0
}

### 图生图: 上传本地图片并创建任务
POST http://127.0.0.1:9000/image-generation/image/img2img HTTP/1.1
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary7MA4YWxkTrZu0gW

--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="prompt"

Change the hair color of the person in the picture to yellow.
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="model_id"

flux.1-dev
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="strength"

0.8
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="width"

1024
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="height"

1024
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="num_inference_steps"

20
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="guidance_scale"

7.5
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="sha256"

8d9cea43b27fe88053835841468d9eb972b8078556e8a62a53fbb8e1a59b59b9
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="input_image"; filename="default.png"
Content-Type: image/png

< ./static/avatar/default.png
--WebKitFormBoundary7MA4YWxkTrZu0gW--

### 取消任务
POST http://127.0.0.1:9000/image-generation/image/cancel
Authorization: {{token}}
Content-Type: application/json

{
  "task_id": "01c21072-47c6-453f-a122-d2b4dbf4c216"
}