// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.11.2
// source: message.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVarifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVarifyReq) Reset() {
	*x = GetVarifyReq{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVarifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVarifyReq) ProtoMessage() {}

func (x *GetVarifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVarifyReq.ProtoReflect.Descriptor instead.
func (*GetVarifyReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *GetVarifyReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetVarifyRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         int32                  `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVarifyRsp) Reset() {
	*x = GetVarifyRsp{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVarifyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVarifyRsp) ProtoMessage() {}

func (x *GetVarifyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVarifyRsp.ProtoReflect.Descriptor instead.
func (*GetVarifyRsp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *GetVarifyRsp) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *GetVarifyRsp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetVarifyRsp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\"$\n" +
	"\fGetVarifyReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"N\n" +
	"\fGetVarifyRsp\x12\x14\n" +
	"\x05error\x18\x01 \x01(\x05R\x05error\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code2P\n" +
	"\rVarifyService\x12?\n" +
	"\rGetVarifyCode\x12\x15.message.GetVarifyReq\x1a\x15.message.GetVarifyRsp\"\x00B3Z1github.com/Zhiruosama/ai_nexus/internal/grpc;grpcb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_proto_goTypes = []any{
	(*GetVarifyReq)(nil), // 0: message.GetVarifyReq
	(*GetVarifyRsp)(nil), // 1: message.GetVarifyRsp
}
var file_message_proto_depIdxs = []int32{
	0, // 0: message.VarifyService.GetVarifyCode:input_type -> message.GetVarifyReq
	1, // 1: message.VarifyService.GetVarifyCode:output_type -> message.GetVarifyRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
