server:
  host: 0.0.0.0
  public: 192.168.20.131
  port: 10001

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: whx
  database: ai_nexus

redis:
  addr: 127.0.0.1:6379
  password: "whx"
  db: 0

ratelimit:
  limitmax: 100
  window: 1m

deduplication:
  lockduration: 5s

grpcclient:
  serveraddress: 127.0.0.1:50002
  defaulttimeout: 10s

rabbitmq:
  host: 127.0.0.1
  port: 5672
  user: guest
  password: guest
  vhost: /

chat:
  encryptionkey: "f97c463636cc9f450bd568d93df7c4e9835c276abcd13118670fd144365fdb22"
  maxmessagesperconv: 200
