server:
  host: 0.0.0.0
  public: 192.168.20.131
  port: 10001

mysql:
  host: 127.0.0.1
  port: 3306
  user: ainexus
  pass: AiNexus@123456
  database: ai_nexus

redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0

ratelimit:
  limitmax: 100
  window: 1m

deduplication:
  lockduration: 5s

grpcclient:
  serveraddress: 127.0.0.1:50002
  defaulttimeout: 10s

rabbitmq:
  host: 127.0.0.1
  port: 5672
  user: guest
  password: guest
  vhost: /