name: Go CI Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-lint:
    name: Build & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Install Dependencies
        run: go mod download

      - name: Verify Dependencies
        run: go mod verify

      - name: Check Code Formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "These file need fmt:"
            gofmt -l .
            exit 1
          fi

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0
          args: --timeout=5m --max-issues-per-linter=0 --max-same-issues=0

      - name: Build
        run: go build -v ./...
        env:
          GOFLAGS: "-buildvcs=false"
          CGO_ENABLED: "0"
        continue-on-error: false
